apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dotnetcoreapi-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /frontend
        backend:
          serviceName: {{ .Release.Name }}-{{ .Values.webAPI.name }}
          servicePort: 80
      - path: /backend
        backend:
          serviceName: {{ .Release.Name }}-{{ .Values.coreWebAPI.name }}
          servicePort: 80