apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dotnetcoreapi-nginx-ingress
spec:
  replicas: 3
  rules:
  - host: mymicroservices.nilayparikh
  - http:
      paths:
      - path: /frontend
        backend:
          serviceName: {{ .Values.webAPI.name }}
          servicePort: 80
      - path: /backend
        backend:
          serviceName: {{ .Values.coreWebAPI.name }}
          servicePort: 80