apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.coreWebAPI.name }}
  labels:
    app: {{ .Values.coreWebAPI.name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.coreWebAPI.name }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webAPI.name }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  webapi_mapping
      prefix: /{{ .Values.webAPI.name }}/
      service: {{ .Values.webAPI.name }}
  labels:
    app: {{ .Values.webAPI.name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.webAPI.name }}
    release: {{ .Release.Name }}