# Default values for APIDeploymentChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

coreWebAPI:
  name: corewebapi
  replicaCount: 2

  image:
    repository: nilayparikh/corewebapi
    tag: helm-intro
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer
    port: 80

webAPI:
  name: webapi
  replicaCount: 2

  image:
    repository: nilayparikh/webapi
    tag: helm-intro
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer
    port: 80