version: '3'

services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile

  corewebapi:
    image: corewebapi
    build:
      context: .
      dockerfile: CoreWebAPI/Dockerfile

