version: '3'

services:
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  corewebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  website:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

