version: '3'

services:
  webapi:
    image: localhost:5000/webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile

  corewebapi:
    image: localhost:5000/corewebapi
    build:
      context: .
      dockerfile: CoreWebAPI/Dockerfile

