version: '3'

services:
  webapi:
    image: nilayparikh/webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "8091:80"
    links:
      - corewebapi

  corewebapi:
    image: nilayparikh/corewebapi
    build:
      context: .
      dockerfile: CoreWebAPI/Dockerfile
    ports:
      - "8090:80"